<?php

/**
 * @file
 * Contains insignregtest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function insignregtest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the insignregtest module.
    case 'help.page.insignregtest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This display information the application.') . '</p>';
      return $output;

    default:
  }
}

